#!/bin/bash

./scripts/bundle-setup.sh

GENERATED_ADOC=generated/stf-spec-github.adoc

bundle exec asciidoctor-reducer -o $GENERATED_ADOC.tmp stf-spec.adoc

# Fix the relative path for the images directory
sed -i 's/:imagesdir: images/:imagesdir: ..\/images/g' $GENERATED_ADOC.tmp

# Add disclaimer comment
cat << EOF | cat - $GENERATED_ADOC.tmp > $GENERATED_ADOC
////
DO NOT EDIT. This file was autogenerated by flatten.sh.
To make changes to this file, edit stf-spec.adoc and then run make.
////
EOF

rm $GENERATED_ADOC.tmp
