#!/bin/bash

INSTALLED_GEMS_PATH=.bundle/gems

if ! command -v ruby &> /dev/null
then
    echo "This script requires ruby to work. Please install it and try again."
fi

if ! command -v bundle &> /dev/null
then
    echo "This script requires bundler to work. Please run:"
    echo "gem install bundler"
    echo "and try again"
fi

if [ ! -d $INSTALLED_GEMS_PATH ]
then
    bundle --path=$INSTALLED_GEMS_PATH
fi

GENERATED_ADOC=generated/stf-spec-github.adoc

bundle exec asciidoctor-reducer -o $GENERATED_ADOC.tmp stf-spec.adoc

# Fix the relative path for the images directory
sed -i 's/:imagesdir: images/:imagesdir: ..\/images/g' $GENERATED_ADOC.tmp

# Add disclaimer comment
cat << EOF | cat - $GENERATED_ADOC.tmp > $GENERATED_ADOC
////
DO NOT EDIT. This file was autogenerated by flatten.sh.
To make changes to this file, edit stf-spec.adoc and then run make.
////
EOF

rm $GENERATED_ADOC.tmp
